using UnityEngine;

public class Sward : MonoBehaviour
{
    public float speed = 100f;//íšŒì „ ì†ë„
    public GameObject arrow_center; // Empty Game Object
    public int damage =10;
    private void Start()
    {

    }
    void Update()
    {
        if (arrow_center != null) // ğŸ”¥ ì¤‘ì‹¬ì´ ì„¤ì •ëœ ê²½ìš°ì—ë§Œ íšŒì „
        {
            transform.RotateAround(arrow_center.transform.position, Vector3.forward, speed * Time.deltaTime);
        }
    }

    private void OnTriggerEnter2D(Collider2D collision)
    {
        if (collision.CompareTag("Enemy"))
        {
            enemy enemyScript = collision.gameObject.GetComponent<enemy>();

            // enemy ìŠ¤í¬ë¦½íŠ¸ê°€ ì¡´ì¬í•˜ë©´ ë°ë¯¸ì§€ë¥¼ ì¤Œ
            if (enemyScript != null)
            {
                enemyScript.Damage(damage);
            }
        }
    }

}
